#!/bin/bash
src=$1
#set -- $(getopt -a src "$@")
#if	[ $? -ne 0 ]
#then	print >&2 "Usage: $0 [-s] [-d seplist] file ..."
#	exit 1
#fi
#for o
#do	case "$o" in
#	-src)	shift; src="$1"; shift;;
	#-s)	paste=hpaste; shift;;
#	--)	shift; break;;
#	esac
#done
echo '<script type="text/javascript" src="'$src'"></script>'
